export const ImageGalleryHtml = () => `
<div class="image-gallery">
    <ul class="grid">
        <li>
            <a
                class="image-gallery__link"
                href="https://dummyimage.com/1920x1080/ccc/ddd"
            >
                <picture>
                    <source
                        srcset="https://dummyimage.com/400x300/ccc/ddd"
                        type="image/webp"
                    >
                    <img
                        class="image"
                        src="https://dummyimage.com/400x300/ccc/ddd"
                        alt="[alt]"
                        loading="lazy"
                        height="300"
                        width="400"
                    />
                </picture>
            </a>
        </li>
        <li>
            <a
                class="image-gallery__link"
                href="https://dummyimage.com/1920x1080/ccc/ddd"
            >
                <picture>
                    <source
                        srcset="https://dummyimage.com/400x300/ccc/ddd"
                        type="image/webp"
                    >
                    <img
                        class="image"
                        src="https://dummyimage.com/400x300/ccc/ddd"
                        alt="[alt]"
                        loading="lazy"
                        height="300"
                        width="400"
                    />
                </picture>
            </a>
        </li>
        <li>
            <a
                class="image-gallery__link"
                href="https://dummyimage.com/1920x1080/ccc/ddd"
            >
                <picture>
                    <source
                        srcset="https://dummyimage.com/400x300/ccc/ddd"
                        type="image/webp"
                    >
                    <img
                        class="image"
                        src="https://dummyimage.com/400x300/ccc/ddd"
                        alt="[alt]"
                        loading="lazy"
                        height="300"
                        width="400"
                    />
                </picture>
            </a>
        </li>
        <li>
            <a
                class="image-gallery__link"
                href="https://dummyimage.com/1920x1080/ccc/ddd"
            >
                <picture>
                    <source
                        srcset="https://dummyimage.com/400x300/ccc/ddd"
                        type="image/webp"
                    >
                    <img
                        class="image"
                        src="https://dummyimage.com/400x300/ccc/ddd"
                        alt="[alt]"
                        loading="lazy"
                        height="300"
                        width="400"
                    />
                </picture>
            </a>
        </li>
        <li>
            <a
                class="image-gallery__link"
                href="https://dummyimage.com/1920x1080/ccc/ddd"
            >
                <picture>
                    <source
                        srcset="https://dummyimage.com/400x300/ccc/ddd"
                        type="image/webp"
                    >
                    <img
                        class="image"
                        src="https://dummyimage.com/400x300/ccc/ddd"
                        alt="[alt]"
                        loading="lazy"
                        height="300"
                        width="400"
                    />
                </picture>
            </a>
        </li>
    </ul>
</div>
`;
